import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';

import { apiClient } from '../lib/apiClient';
import { useEffect } from 'react';

import { useQueryClient, useMutation } from 'react-query'
import {useAspidaQuery} from "@aspida/react-query";
// import { useAspidaQuery } from "@aspida/react-query"
// import aspida from "@aspida/axios" // "@aspida/fetch", "@aspida/node-fetch"
// import api from "../api/$api"

const Home: NextPage = () => {
  const queryClient = useQueryClient()

  // .get がコールされた結果を受け取る
  const {data:pollData ,refetch:pollRefetch} = useAspidaQuery(apiClient.api.polls.questions,{});
  console.log('res1', pollData,pollRefetch);

  useEffect(() => {
    const fetchArticle = async () => {
      // $ つきの場合は response.body を自動で展開してくれる
      // const res2 = await apiClient.api.polls.questions.get();
      // console.log('res2', res2);
      // create
      // const res3 = await apiClient.polls.questions.$post({
      //     body:{
      //         question_text: "test",
      //         pub_date: "2022-06-07T01:26:56.937Z",
      //     }
      // })
      // console.log("res3", res3)

      // patch
      // const res4 =await apiClient.polls.questions._id(16).$patch({
      //     body:{ question_text:"upd" }
      // })
      // console.log("res4",res4);

      // delete
      // const res4 =await apiClient.polls.questions._id(17).$delete()
      // console.log("res4",res4);
    };
    fetchArticle();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href='https://github.com/vercel/next.js/tree/canary/examples' className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
